// Generated once from ISO 3166-1 (countries) with their ISO 3166 alpha-3 code and the currency each uses (null: none).
// [alpha-2, alpha-3, name, currency]
export const COUNTRY_DATA: [string, string, string, string | null][] = [
  ["AF","AFG","Afghanistan","AFN"],
  ["AX","ALA","Åland Islands","EUR"],
  ["AL","ALB","Albania","ALL"],
  ["DZ","DZA","Algeria","DZD"],
  ["AS","ASM","American Samoa","USD"],
  ["AD","AND","Andorra","EUR"],
  ["AO","AGO","Angola","AOA"],
  ["AI","AIA","Anguilla","XCD"],
  ["AQ","ATA","Antarctica",null],
  ["AG","ATG","Antigua & Barbuda","XCD"],
  ["AR","ARG","Argentina","ARS"],
  ["AM","ARM","Armenia","AMD"],
  ["AW","ABW","Aruba","AWG"],
  ["AU","AUS","Australia","AUD"],
  ["AT","AUT","Austria","EUR"],
  ["AZ","AZE","Azerbaijan","AZN"],
  ["BS","BHS","Bahamas","BSD"],
  ["BH","BHR","Bahrain","BHD"],
  ["BD","BGD","Bangladesh","BDT"],
  ["BB","BRB","Barbados","BBD"],
  ["BY","BLR","Belarus","BYN"],
  ["BE","BEL","Belgium","EUR"],
  ["BZ","BLZ","Belize","BZD"],
  ["BJ","BEN","Benin","XOF"],
  ["BM","BMU","Bermuda","BMD"],
  ["BT","BTN","Bhutan","BTN"],
  ["BO","BOL","Bolivia","BOB"],
  ["BA","BIH","Bosnia & Herzegovina","BAM"],
  ["BW","BWA","Botswana","BWP"],
  ["BV","BVT","Bouvet Island","NOK"],
  ["BR","BRA","Brazil","BRL"],
  ["IO","IOT","British Indian Ocean Territory","USD"],
  ["VG","VGB","British Virgin Islands","USD"],
  ["BN","BRN","Brunei","BND"],
  ["BG","BGR","Bulgaria","EUR"],
  ["BF","BFA","Burkina Faso","XOF"],
  ["BI","BDI","Burundi","BIF"],
  ["KH","KHM","Cambodia","KHR"],
  ["CM","CMR","Cameroon","XAF"],
  ["CA","CAN","Canada","CAD"],
  ["CV","CPV","Cape Verde","CVE"],
  ["BQ","BES","Caribbean Netherlands","USD"],
  ["KY","CYM","Cayman Islands","KYD"],
  ["CF","CAF","Central African Republic","XAF"],
  ["TD","TCD","Chad","XAF"],
  ["CL","CHL","Chile","CLP"],
  ["CN","CHN","China","CNY"],
  ["CX","CXR","Christmas Island","AUD"],
  ["CC","CCK","Cocos (Keeling) Islands","AUD"],
  ["CO","COL","Colombia","COP"],
  ["KM","COM","Comoros","KMF"],
  ["CG","COG","Congo - Brazzaville","XAF"],
  ["CD","COD","Congo - Kinshasa","CDF"],
  ["CK","COK","Cook Islands","NZD"],
  ["CR","CRI","Costa Rica","CRC"],
  ["CI","CIV","Côte d’Ivoire","XOF"],
  ["HR","HRV","Croatia","EUR"],
  ["CU","CUB","Cuba","CUP"],
  ["CW","CUW","Curaçao","ANG"],
  ["CY","CYP","Cyprus","EUR"],
  ["CZ","CZE","Czechia","CZK"],
  ["DK","DNK","Denmark","DKK"],
  ["DJ","DJI","Djibouti","DJF"],
  ["DM","DMA","Dominica","XCD"],
  ["DO","DOM","Dominican Republic","DOP"],
  ["EC","ECU","Ecuador","USD"],
  ["EG","EGY","Egypt","EGP"],
  ["SV","SLV","El Salvador","USD"],
  ["GQ","GNQ","Equatorial Guinea","XAF"],
  ["ER","ERI","Eritrea","ERN"],
  ["EE","EST","Estonia","EUR"],
  ["SZ","SWZ","Eswatini","SZL"],
  ["ET","ETH","Ethiopia","ETB"],
  ["FK","FLK","Falkland Islands","FKP"],
  ["FO","FRO","Faroe Islands","DKK"],
  ["FJ","FJI","Fiji","FJD"],
  ["FI","FIN","Finland","EUR"],
  ["FR","FRA","France","EUR"],
  ["GF","GUF","French Guiana","EUR"],
  ["PF","PYF","French Polynesia","XPF"],
  ["TF","ATF","French Southern Territories","EUR"],
  ["GA","GAB","Gabon","XAF"],
  ["GM","GMB","Gambia","GMD"],
  ["GE","GEO","Georgia","GEL"],
  ["DE","DEU","Germany","EUR"],
  ["GH","GHA","Ghana","GHS"],
  ["GI","GIB","Gibraltar","GIP"],
  ["GR","GRC","Greece","EUR"],
  ["GL","GRL","Greenland","DKK"],
  ["GD","GRD","Grenada","XCD"],
  ["GP","GLP","Guadeloupe","EUR"],
  ["GU","GUM","Guam","USD"],
  ["GT","GTM","Guatemala","GTQ"],
  ["GG","GGY","Guernsey","GBP"],
  ["GN","GIN","Guinea","GNF"],
  ["GW","GNB","Guinea-Bissau","XOF"],
  ["GY","GUY","Guyana","GYD"],
  ["HT","HTI","Haiti","HTG"],
  ["HM","HMD","Heard & McDonald Islands","AUD"],
  ["HN","HND","Honduras","HNL"],
  ["HK","HKG","Hong Kong SAR China","HKD"],
  ["HU","HUN","Hungary","HUF"],
  ["IS","ISL","Iceland","ISK"],
  ["IN","IND","India","INR"],
  ["ID","IDN","Indonesia","IDR"],
  ["IR","IRN","Iran","IRR"],
  ["IQ","IRQ","Iraq","IQD"],
  ["IE","IRL","Ireland","EUR"],
  ["IM","IMN","Isle of Man","GBP"],
  ["IL","ISR","Israel","ILS"],
  ["IT","ITA","Italy","EUR"],
  ["JM","JAM","Jamaica","JMD"],
  ["JP","JPN","Japan","JPY"],
  ["JE","JEY","Jersey","GBP"],
  ["JO","JOR","Jordan","JOD"],
  ["KZ","KAZ","Kazakhstan","KZT"],
  ["KE","KEN","Kenya","KES"],
  ["KI","KIR","Kiribati","AUD"],
  ["KW","KWT","Kuwait","KWD"],
  ["KG","KGZ","Kyrgyzstan","KGS"],
  ["LA","LAO","Laos","LAK"],
  ["LV","LVA","Latvia","EUR"],
  ["LB","LBN","Lebanon","LBP"],
  ["LS","LSO","Lesotho","LSL"],
  ["LR","LBR","Liberia","LRD"],
  ["LY","LBY","Libya","LYD"],
  ["LI","LIE","Liechtenstein","CHF"],
  ["LT","LTU","Lithuania","EUR"],
  ["LU","LUX","Luxembourg","EUR"],
  ["MO","MAC","Macao SAR China","MOP"],
  ["MG","MDG","Madagascar","MGA"],
  ["MW","MWI","Malawi","MWK"],
  ["MY","MYS","Malaysia","MYR"],
  ["MV","MDV","Maldives","MVR"],
  ["ML","MLI","Mali","XOF"],
  ["MT","MLT","Malta","EUR"],
  ["MH","MHL","Marshall Islands","USD"],
  ["MQ","MTQ","Martinique","EUR"],
  ["MR","MRT","Mauritania","MRU"],
  ["MU","MUS","Mauritius","MUR"],
  ["YT","MYT","Mayotte","EUR"],
  ["MX","MEX","Mexico","MXN"],
  ["FM","FSM","Micronesia","USD"],
  ["MD","MDA","Moldova","MDL"],
  ["MC","MCO","Monaco","EUR"],
  ["MN","MNG","Mongolia","MNT"],
  ["ME","MNE","Montenegro","EUR"],
  ["MS","MSR","Montserrat","XCD"],
  ["MA","MAR","Morocco","MAD"],
  ["MZ","MOZ","Mozambique","MZN"],
  ["MM","MMR","Myanmar (Burma)","MMK"],
  ["NA","NAM","Namibia","NAD"],
  ["NR","NRU","Nauru","AUD"],
  ["NP","NPL","Nepal","NPR"],
  ["NL","NLD","Netherlands","EUR"],
  ["NC","NCL","New Caledonia","XPF"],
  ["NZ","NZL","New Zealand","NZD"],
  ["NI","NIC","Nicaragua","NIO"],
  ["NE","NER","Niger","XOF"],
  ["NG","NGA","Nigeria","NGN"],
  ["NU","NIU","Niue","NZD"],
  ["NF","NFK","Norfolk Island","AUD"],
  ["KP","PRK","North Korea","KPW"],
  ["MK","MKD","North Macedonia","MKD"],
  ["MP","MNP","Northern Mariana Islands","USD"],
  ["NO","NOR","Norway","NOK"],
  ["OM","OMN","Oman","OMR"],
  ["PK","PAK","Pakistan","PKR"],
  ["PW","PLW","Palau","USD"],
  ["PS","PSE","Palestinian Territories","ILS"],
  ["PA","PAN","Panama","PAB"],
  ["PG","PNG","Papua New Guinea","PGK"],
  ["PY","PRY","Paraguay","PYG"],
  ["PE","PER","Peru","PEN"],
  ["PH","PHL","Philippines","PHP"],
  ["PN","PCN","Pitcairn Islands","NZD"],
  ["PL","POL","Poland","PLN"],
  ["PT","PRT","Portugal","EUR"],
  ["PR","PRI","Puerto Rico","USD"],
  ["QA","QAT","Qatar","QAR"],
  ["RE","REU","Réunion","EUR"],
  ["RO","ROU","Romania","RON"],
  ["RU","RUS","Russia","RUB"],
  ["RW","RWA","Rwanda","RWF"],
  ["WS","WSM","Samoa","WST"],
  ["SM","SMR","San Marino","EUR"],
  ["ST","STP","São Tomé & Príncipe","STN"],
  ["SA","SAU","Saudi Arabia","SAR"],
  ["SN","SEN","Senegal","XOF"],
  ["RS","SRB","Serbia","RSD"],
  ["SC","SYC","Seychelles","SCR"],
  ["SL","SLE","Sierra Leone","SLE"],
  ["SG","SGP","Singapore","SGD"],
  ["SX","SXM","Sint Maarten","ANG"],
  ["SK","SVK","Slovakia","EUR"],
  ["SI","SVN","Slovenia","EUR"],
  ["SB","SLB","Solomon Islands","SBD"],
  ["SO","SOM","Somalia","SOS"],
  ["ZA","ZAF","South Africa","ZAR"],
  ["GS","SGS","South Georgia & South Sandwich Islands","GBP"],
  ["KR","KOR","South Korea","KRW"],
  ["SS","SSD","South Sudan","SSP"],
  ["ES","ESP","Spain","EUR"],
  ["LK","LKA","Sri Lanka","LKR"],
  ["BL","BLM","St. Barthélemy","EUR"],
  ["SH","SHN","St. Helena","SHP"],
  ["KN","KNA","St. Kitts & Nevis","XCD"],
  ["LC","LCA","St. Lucia","XCD"],
  ["MF","MAF","St. Martin","EUR"],
  ["PM","SPM","St. Pierre & Miquelon","EUR"],
  ["VC","VCT","St. Vincent & Grenadines","XCD"],
  ["SD","SDN","Sudan","SDG"],
  ["SR","SUR","Suriname","SRD"],
  ["SJ","SJM","Svalbard & Jan Mayen","NOK"],
  ["SE","SWE","Sweden","SEK"],
  ["CH","CHE","Switzerland","CHF"],
  ["SY","SYR","Syria","SYP"],
  ["TW","TWN","Taiwan","TWD"],
  ["TJ","TJK","Tajikistan","TJS"],
  ["TZ","TZA","Tanzania","TZS"],
  ["TH","THA","Thailand","THB"],
  ["TL","TLS","Timor-Leste","USD"],
  ["TG","TGO","Togo","XOF"],
  ["TK","TKL","Tokelau","NZD"],
  ["TO","TON","Tonga","TOP"],
  ["TT","TTO","Trinidad & Tobago","TTD"],
  ["TN","TUN","Tunisia","TND"],
  ["TR","TUR","Türkiye","TRY"],
  ["TM","TKM","Turkmenistan","TMT"],
  ["TC","TCA","Turks & Caicos Islands","USD"],
  ["TV","TUV","Tuvalu","AUD"],
  ["UM","UMI","U.S. Outlying Islands","USD"],
  ["VI","VIR","U.S. Virgin Islands","USD"],
  ["UG","UGA","Uganda","UGX"],
  ["UA","UKR","Ukraine","UAH"],
  ["AE","ARE","United Arab Emirates","AED"],
  ["GB","GBR","United Kingdom","GBP"],
  ["US","USA","United States","USD"],
  ["UY","URY","Uruguay","UYU"],
  ["UZ","UZB","Uzbekistan","UZS"],
  ["VU","VUT","Vanuatu","VUV"],
  ["VA","VAT","Vatican City","EUR"],
  ["VE","VEN","Venezuela","VES"],
  ["VN","VNM","Vietnam","VND"],
  ["WF","WLF","Wallis & Futuna","XPF"],
  ["EH","ESH","Western Sahara","MAD"],
  ["YE","YEM","Yemen","YER"],
  ["ZM","ZMB","Zambia","ZMW"],
  ["ZW","ZWE","Zimbabwe","ZWG"],
];
